[package]
name = "fmnist-sample"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensorflow = "0.16.1"
anyhow = "1.0.41"
image = "0.23.14"
structopt = "0.3.21"
glob = "0.3.0"
